### ISSUE TITLE
typo in fileName-type mismatch for yauzl.Entry

### ISSUE THREAD

**Issue by capaj** [overlookmotel/yauzl-promise#42]
This runs correctly at runtime:
![image](https://github.com/overlookmotel/yauzl-promise/assets/1305378/b4cfc770-c559-42d3-83ce-98f6ab6b8f29)

if I try to fix the types by renaming `filename` to `fileName`  typescript is happy, but at runtime it crashes.

**Comment by capaj** [comment]
oh shoot it's community types, so I should not have created it here, sorry

**Comment by overlookmotel** [comment]
No worries. I should probably include types within the package, but I'm not that familiar with TypeScript, so a bit nervous about doing that. Would welcome a PR.
