### ISSUE TITLE
Type definitions for Entry are incorrect for filename

### ISSUE THREAD

**Issue by zz-kivo** [overlookmotel/yauzl-promise#43]
The type definition for Entry in DefinitelyTyped is extending the base entry from yauzl. 

The type has fileName as a property, however, yauzl-promise has changed this property to filename.

**Comment by overlookmotel** [comment]
Yes, this change vs original `yauzl` is highlighted at the top of the README. It's a feature not a bug!

As mentioned in #42, I would welcome a PR to add type defs to this library. Please let me know if you'd like to do that.

**Comment by zz-kivo** [comment]
Sorry bout that, I see a few comments around this in closed issues. I'll submit a pr to update the type definitions over in DefinitelyTyped.

**Comment by overlookmotel** [comment]
Thanks @zz-kivo. You're not the first to complain about the types, and I'm sure you won't be the last! It'd be great if you'd be able to bring the types in DefinitelyTyped up to speed.
